import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const quotes = [
      {
        id: 1,
        userId: 158010,
        firstName: 'Russell',
        lastName: 'Dow',
        dateOfBirth: new Date('08/15/1988'),
        email: 'russell.j.dow@avanade.com',
        phone: '2063066808',
        address: '24245 183rd ave se',
        city: 'Covington',
        state: 'WA',
        zip: '98042',
        ssn: '333224444',
        price: 1298.70,
        dateQuoted: '08/31/2018',
        sold: false,
        dateSold: null,
        discarded: false,
        dateDiscarded: null,
        previousCarrier: 'Lizard',
        pastClaims: true,
        pastClaimsDiscount: 0.02,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.15,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
        drivers: [
          {
            id: 1,
            quoteId: 1,
            firstName: 'Russell',
            lastName: 'Dow',
            dateOfBirth: new Date('08/15/1988'),
            licenseNumber: 'DOWRJ**132NN',
            issuingState: 'WA',
            safeDrivingSchool: true,
            safeDrivingSchoolDiscount: -0.05,
            under23YearsOld: false,
            under23YearsOldDiscount: null,
          },
          {
            id: 2,
            quoteId: 1,
            firstName: 'Kelvin',
            lastName: 'Celcius',
            dateOfBirth: new Date('08/12/1908'),
            licenseNumber: 'KCEL**132NN',
            issuingState: 'WA',
            safeDrivingSchool: true,
            safeDrivingSchoolDiscount: -0.05,
            under23YearsOld: false,
            under23YearsOldDiscount: null,
          }
        ],
        vehicles: [
          {
            id: 1,
            quoteId: 1,
            primaryDriver: 'Russell',
            primaryDriverId: 1,
            vin: 'GHURI837HD73YUW72',
            make: 'Toyota',
            model: 'Corolla',
            year: 2017,
            currentValue: 18988,
            milesToWork: 22,
            annualMileage: 10400,
            daysDrivenPerWeek: 5,
            antiTheft: true,
            antiTheftDiscount: -0.05,
            antilockBrakes: true,
            antilockBrakesDiscount: -0.06,
            daytimeLights: true,
            daytimeLightsDiscount: -0.03,
            nonResidenceGarage: false,
            nonResidenceGarageDiscount: null,
            passiveRestraints: true,
            passiveRestraintsDiscount: -0.04,
            reducedUsed: false,
            reducedUsedDiscount: null,
            annualMileageUnder6k: false,
            annualMileageUnder6kDiscount: null,
            daysDrivenPerWeekOver4: true,
            daysDrivenPerWeekOver4Discount: 0.05,
            milesToWorkUnder26: true,
            milesToWorkUnder26Discount: -0.02,
          },
          {
            id: 2,
            quoteId: 1,
            primaryDriver: 'Kelvin',
            primaryDriverId: 2,
            vin: 'GHURI837HJF*#UW72',
            make: 'Dodge',
            model: 'Dart',
            year: 2016,
            currentValue: 11988,
            milesToWork: 26,
            annualMileage: 12400,
            daysDrivenPerWeek: 4,
            antiTheft: true,
            antiTheftDiscount: -0.05,
            antilockBrakes: true,
            antilockBrakesDiscount: -0.06,
            daytimeLights: true,
            daytimeLightsDiscount: -0.03,
            nonResidenceGarage: false,
            nonResidenceGarageDiscount: null,
            passiveRestraints: true,
            passiveRestraintsDiscount: -0.04,
            reducedUsed: false,
            reducedUsedDiscount: null,
            annualMileageUnder6k: false,
            annualMileageUnder6kDiscount: null,
            daysDrivenPerWeekOver4: false,
            daysDrivenPerWeekOver4Discount: null,
            milesToWorkUnder26: true,
            milesToWorkUnder26Discount: -0.02,
          }
        ],
      },
      {
        id: 2,
        userId: 158011,
        firstName: 'Roger',
        lastName: 'Dodger',
        dateOfBirth: new Date('01/15/1988'),
        email: 'rdodger@gmail.com',
        phone: '2064005898',
        address: '19218 42nd st s',
        city: 'Kent',
        state: 'WA',
        zip: '98043',
        ssn: '333114444',
        price: 1290.70,
        dateQuoted: '08/31/2018',
        sold: false,
        dateSold: null,
        discarded: true,
        dateDiscarded: new Date('08/30/2018'),
        previousCarrier: 'Lizard',
        pastClaims: false,
        pastClaimsDiscount: null,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.05,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
        drivers: [],
        vehicles: [],
      },
      {
        id: 3,
        userId: 152011,
        firstName: 'Arthur',
        lastName: 'Chrone',
        dateOfBirth: new Date('01/12/1982'),
        email: 'achrone@gmail.com',
        phone: '2064115898',
        address: '19318 82nd st s',
        city: 'Seattle',
        state: 'WA',
        zip: '98038',
        ssn: '313224444',
        price: 1190.70,
        dateQuoted: '08/29/2018',
        sold: false,
        dateSold: null,
        discarded: false,
        dateDiscarded: null,
        previousCarrier: 'Pervasive',
        pastClaims: false,
        pastClaimsDiscount: null,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.05,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
        drivers: [],
        vehicles: [],
      },
    ];

    const drivers = [
      {
        id: 1,
        quoteId: 1,
        firstName: 'Russell',
        lastName: 'Dow',
        dateOfBirth: new Date('08/15/1988'),
        licenseNumber: 'DOWRJ**132NN',
        issuingState: 'WA',
        safeDrivingSchool: true,
        safeDrivingSchoolDiscount: -0.05,
        under23YearsOld: false,
        under23YearsOldDiscount: null,
      },
      {
        id: 2,
        quoteId: 1,
        firstName: 'Kelvin',
        lastName: 'Celcius',
        dateOfBirth: new Date('08/12/1908'),
        licenseNumber: 'KCEL**132NN',
        issuingState: 'WA',
        safeDrivingSchool: true,
        safeDrivingSchoolDiscount: -0.05,
        under23YearsOld: false,
        under23YearsOldDiscount: null,
      }
    ];

    const vehicles = [
      {
        id: 1,
        quoteId: 1,
        primaryDriver: 'Russell',
        primaryDriverId: 1,
        vin: 'GHURI837HD73YUW72',
        make: 'Toyota',
        model: 'Corolla',
        year: 2017,
        currentValue: 18988,
        milesToWork: 22,
        annualMileage: 10400,
        daysDrivenPerWeek: 5,
        antiTheft: true,
        antiTheftDiscount: -0.05,
        antilockBrakes: true,
        antilockBrakesDiscount: -0.06,
        daytimeLights: true,
        daytimeLightsDiscount: -0.03,
        nonResidenceGarage: false,
        nonResidenceGarageDiscount: null,
        passiveRestraints: true,
        passiveRestraintsDiscount: -0.04,
        reducedUsed: false,
        reducedUsedDiscount: null,
        annualMileageUnder6k: false,
        annualMileageUnder6kDiscount: null,
        daysDrivenPerWeekOver4: true,
        daysDrivenPerWeekOver4Discount: 0.05,
        milesToWorkUnder26: true,
        milesToWorkUnder26Discount: -0.02,
      },
      {
        id: 2,
        quoteId: 1,
        primaryDriver: 'Kelvin',
        primaryDriverId: 2,
        vin: 'GHURI837HJF*#UW72',
        make: 'Dodge',
        model: 'Dart',
        year: 2016,
        currentValue: 11988,
        milesToWork: 26,
        annualMileage: 12400,
        daysDrivenPerWeek: 4,
        antiTheft: true,
        antiTheftDiscount: -0.05,
        antilockBrakes: true,
        antilockBrakesDiscount: -0.06,
        daytimeLights: true,
        daytimeLightsDiscount: -0.03,
        nonResidenceGarage: false,
        nonResidenceGarageDiscount: null,
        passiveRestraints: true,
        passiveRestraintsDiscount: -0.04,
        reducedUsed: false,
        reducedUsedDiscount: null,
        annualMileageUnder6k: false,
        annualMileageUnder6kDiscount: null,
        daysDrivenPerWeekOver4: false,
        daysDrivenPerWeekOver4Discount: null,
        milesToWorkUnder26: true,
        milesToWorkUnder26Discount: -0.02,
      }
    ];
    return {quotes, drivers, vehicles};
  }
}
